name: C Lint

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get -y install cppcheck

    - name: Run cppcheck
      run: cppcheck --quiet --language=c .

  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Clang and dependencies
      run: sudo apt-get install -y clang-tools
      
    - name: Update submodule
      run: git submodule update --init --recursive

    - name: Run Clang Static Analyzer
      run: scan-build make